spring.application.name=groceryapp

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/grocery_app
spring.datasource.username=root
spring.datasource.password=Pass@3110

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Server Port (optional)
server.port=8080
