spring.application.name=budgettracker
# ===============================
# DATABASE CONNECTION
# ===============================
spring.datasource.url=jdbc:mysql://mysql:3306/budget_tracker
spring.datasource.username=root
spring.datasource.password=Pass@3110

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# SERVER
# ===============================
server.port=8080
