version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: library_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Pass@3110
      MYSQL_DATABASE: librarydb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: library_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/librarydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Pass@3110

  frontend:
    build: ./frontend
    container_name: library_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data: